### ISSUE TITLE
Move nrf52840-hal to dev-dependencies

### ISSUE THREAD

**Issue by keisrk** [nihalpasham/Rusty_CryptoAuthLib#2]
Hi there, thanks for the nice project!

I'm working with stm32l432xx series chips with ATECC608a. And I'm seeing a 
problem with the [dependency in Cargo.toml](https://github.com/nihalpasham/Rusty_CryptoAuthLib/blob/master/Cargo.toml#L18-L19).
It seems that the dependency of `nrf52840-hal` doesn't coexist with other
HAL implementations. Below is an excerpt from the compile error.

```
error: linking with `rust-lld` failed: exit code: 1                                                       
  |                                                                                                       
  = note: "rust-lld" "-flavor" "gnu" "--eh-frame-hdr" "-L" ...
  = note: rust-lld: error: undefined symbol: WWDG                                                         
          >>> referenced by ...
           
          rust-lld: error: undefined symbol: PVD   
          >>> referenced by ...
```

And once I moved it under `dev-dependencies` section, it worked as expected.
Please find the corresponding PR #1. I am happy to take care of this :)

**Comment by nihalpasham** [comment]
Guess, I missed this. Thanks for the PR 👍
